// Mocks generated by Mockito 5.4.4 from annotations
// in personal_finance_tracker/test/infrastructure/services/category_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_finance_tracker/domain/entities/category.dart' as _i2;
import 'package:personal_finance_tracker/domain/entities/transaction.dart'
    as _i3;
import 'package:personal_finance_tracker/domain/value_objects/date_range.dart'
    as _i7;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/category_local_data_source.dart'
    as _i4;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/transaction_local_data_source.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_1 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryLocalDataSource extends _i1.Mock
    implements _i4.CategoryLocalDataSource {
  MockCategoryLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Category> create(_i2.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [category],
        ),
        returnValue: _i5.Future<_i2.Category>.value(_FakeCategory_0(
          this,
          Invocation.method(
            #create,
            [category],
          ),
        )),
      ) as _i5.Future<_i2.Category>);

  @override
  _i5.Future<_i2.Category> update(_i2.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [category],
        ),
        returnValue: _i5.Future<_i2.Category>.value(_FakeCategory_0(
          this,
          Invocation.method(
            #update,
            [category],
          ),
        )),
      ) as _i5.Future<_i2.Category>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Category?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Category?>.value(),
      ) as _i5.Future<_i2.Category?>);

  @override
  _i5.Future<List<_i2.Category>> getAll({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<List<_i2.Category>> getDefaultCategories({String? locale}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultCategories,
          [],
          {#locale: locale},
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<List<_i2.Category>> getCustomCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomCategories,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<List<_i2.Category>> getRootCategories({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRootCategories,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<List<_i2.Category>> getChildCategories({
    required String? parentCategoryId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildCategories,
          [],
          {
            #parentCategoryId: parentCategoryId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<Map<_i2.Category, List<_i2.Category>>> getCategoryHierarchy(
          {String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryHierarchy,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<Map<_i2.Category, List<_i2.Category>>>.value(
            <_i2.Category, List<_i2.Category>>{}),
      ) as _i5.Future<Map<_i2.Category, List<_i2.Category>>>);

  @override
  _i5.Future<bool> hasChildren(
    String? categoryId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasChildren,
          [categoryId],
          {#userId: userId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.Category>> getAncestors(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAncestors,
          [categoryId],
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<bool> hasCircularReference(
    String? categoryId,
    String? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasCircularReference,
          [
            categoryId,
            parentId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Stream<List<_i2.Category>> watchAll({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Stream<List<_i2.Category>>.empty(),
      ) as _i5.Stream<List<_i2.Category>>);

  @override
  _i5.Future<int> getCount({String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> clearCustomCategories(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearCustomCategories,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchCreate(List<_i2.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [categories],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchUpdate(List<_i2.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [categories],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TransactionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDataSource extends _i1.Mock
    implements _i6.TransactionLocalDataSource {
  MockTransactionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Transaction> create(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [transaction],
        ),
        returnValue: _i5.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #create,
            [transaction],
          ),
        )),
      ) as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.Transaction> update(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [transaction],
        ),
        returnValue: _i5.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #update,
            [transaction],
          ),
        )),
      ) as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Transaction?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Transaction?>.value(),
      ) as _i5.Future<_i3.Transaction?>);

  @override
  _i5.Future<List<_i3.Transaction>> getAll({
    required String? userId,
    _i7.DateRange? dateRange,
    String? categoryId,
    _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i5.Future<List<_i3.Transaction>>);

  @override
  _i5.Future<List<_i3.Transaction>> getByDateRange({
    required String? userId,
    required _i7.DateRange? dateRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDateRange,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i5.Future<List<_i3.Transaction>>);

  @override
  _i5.Future<List<_i3.Transaction>> getByCategory({
    required String? userId,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [],
          {
            #userId: userId,
            #categoryId: categoryId,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i5.Future<List<_i3.Transaction>>);

  @override
  _i5.Future<List<_i3.Transaction>> getByType({
    required String? userId,
    required _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [],
          {
            #userId: userId,
            #type: type,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i5.Future<List<_i3.Transaction>>);

  @override
  _i5.Future<List<_i3.Transaction>> getPendingSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSync,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i5.Future<List<_i3.Transaction>>);

  @override
  _i5.Future<List<_i3.Transaction>> getConflicts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i5.Future<List<_i3.Transaction>>);

  @override
  _i5.Stream<List<_i3.Transaction>> watchAll({
    required String? userId,
    _i7.DateRange? dateRange,
    String? categoryId,
    _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue: _i5.Stream<List<_i3.Transaction>>.empty(),
      ) as _i5.Stream<List<_i3.Transaction>>);

  @override
  _i5.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> clearAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchCreate(List<_i3.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [transactions],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchUpdate(List<_i3.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [transactions],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
