// Mocks generated by Mockito 5.4.4 from annotations
// in personal_finance_tracker/test/infrastructure/services/currency_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i5;
import 'dart:typed_data' as _i7;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:personal_finance_tracker/domain/value_objects/currency.dart'
    as _i9;
import 'package:personal_finance_tracker/domain/value_objects/exchange_rate.dart'
    as _i3;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/exchange_rate_local_data_source.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExchangeRate_2 extends _i1.SmartFake implements _i3.ExchangeRate {
  _FakeExchangeRate_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i7.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i4.Future<_i7.Uint8List>);

  @override
  _i4.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ExchangeRateLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateLocalDataSource extends _i1.Mock
    implements _i8.ExchangeRateLocalDataSource {
  MockExchangeRateLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.ExchangeRate> store(_i3.ExchangeRate? rate) =>
      (super.noSuchMethod(
        Invocation.method(
          #store,
          [rate],
        ),
        returnValue: _i4.Future<_i3.ExchangeRate>.value(_FakeExchangeRate_2(
          this,
          Invocation.method(
            #store,
            [rate],
          ),
        )),
      ) as _i4.Future<_i3.ExchangeRate>);

  @override
  _i4.Future<_i3.ExchangeRate?> getRate({
    required _i9.Currency? baseCurrency,
    required _i9.Currency? targetCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRate,
          [],
          {
            #baseCurrency: baseCurrency,
            #targetCurrency: targetCurrency,
          },
        ),
        returnValue: _i4.Future<_i3.ExchangeRate?>.value(),
      ) as _i4.Future<_i3.ExchangeRate?>);

  @override
  _i4.Future<_i3.ExchangeRate?> getValidRate({
    required _i9.Currency? baseCurrency,
    required _i9.Currency? targetCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getValidRate,
          [],
          {
            #baseCurrency: baseCurrency,
            #targetCurrency: targetCurrency,
          },
        ),
        returnValue: _i4.Future<_i3.ExchangeRate?>.value(),
      ) as _i4.Future<_i3.ExchangeRate?>);

  @override
  _i4.Future<List<_i3.ExchangeRate>> getRatesForBase(
          _i9.Currency? baseCurrency) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRatesForBase,
          [baseCurrency],
        ),
        returnValue:
            _i4.Future<List<_i3.ExchangeRate>>.value(<_i3.ExchangeRate>[]),
      ) as _i4.Future<List<_i3.ExchangeRate>>);

  @override
  _i4.Future<List<_i3.ExchangeRate>> getValidRatesForBase(
          _i9.Currency? baseCurrency) =>
      (super.noSuchMethod(
        Invocation.method(
          #getValidRatesForBase,
          [baseCurrency],
        ),
        returnValue:
            _i4.Future<List<_i3.ExchangeRate>>.value(<_i3.ExchangeRate>[]),
      ) as _i4.Future<List<_i3.ExchangeRate>>);

  @override
  _i4.Future<List<_i3.ExchangeRate>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i4.Future<List<_i3.ExchangeRate>>.value(<_i3.ExchangeRate>[]),
      ) as _i4.Future<List<_i3.ExchangeRate>>);

  @override
  _i4.Future<List<_i3.ExchangeRate>> getAllValid() => (super.noSuchMethod(
        Invocation.method(
          #getAllValid,
          [],
        ),
        returnValue:
            _i4.Future<List<_i3.ExchangeRate>>.value(<_i3.ExchangeRate>[]),
      ) as _i4.Future<List<_i3.ExchangeRate>>);

  @override
  _i4.Future<List<_i3.ExchangeRate>> getAllExpired() => (super.noSuchMethod(
        Invocation.method(
          #getAllExpired,
          [],
        ),
        returnValue:
            _i4.Future<List<_i3.ExchangeRate>>.value(<_i3.ExchangeRate>[]),
      ) as _i4.Future<List<_i3.ExchangeRate>>);

  @override
  _i4.Future<bool> hasValidRate({
    required _i9.Currency? baseCurrency,
    required _i9.Currency? targetCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasValidRate,
          [],
          {
            #baseCurrency: baseCurrency,
            #targetCurrency: targetCurrency,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLastUpdateTime({
    required _i9.Currency? baseCurrency,
    required _i9.Currency? targetCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastUpdateTime,
          [],
          {
            #baseCurrency: baseCurrency,
            #targetCurrency: targetCurrency,
          },
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<DateTime?> getLatestUpdateTime() => (super.noSuchMethod(
        Invocation.method(
          #getLatestUpdateTime,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> delete({
    required _i9.Currency? baseCurrency,
    required _i9.Currency? targetCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #baseCurrency: baseCurrency,
            #targetCurrency: targetCurrency,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> deleteExpired() => (super.noSuchMethod(
        Invocation.method(
          #deleteExpired,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> batchStore(List<_i3.ExchangeRate>? rates) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchStore,
          [rates],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> storeRatesForBase({
    required _i9.Currency? baseCurrency,
    required Map<_i9.Currency, _i3.ExchangeRate>? rates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeRatesForBase,
          [],
          {
            #baseCurrency: baseCurrency,
            #rates: rates,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getCount() => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getValidCount() => (super.noSuchMethod(
        Invocation.method(
          #getValidCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getExpiredCount() => (super.noSuchMethod(
        Invocation.method(
          #getExpiredCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Stream<List<_i3.ExchangeRate>> watchAll() => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
        ),
        returnValue: _i4.Stream<List<_i3.ExchangeRate>>.empty(),
      ) as _i4.Stream<List<_i3.ExchangeRate>>);

  @override
  _i4.Stream<_i3.ExchangeRate?> watchRate({
    required _i9.Currency? baseCurrency,
    required _i9.Currency? targetCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRate,
          [],
          {
            #baseCurrency: baseCurrency,
            #targetCurrency: targetCurrency,
          },
        ),
        returnValue: _i4.Stream<_i3.ExchangeRate?>.empty(),
      ) as _i4.Stream<_i3.ExchangeRate?>);

  @override
  _i4.Future<bool> needsRefresh() => (super.noSuchMethod(
        Invocation.method(
          #needsRefresh,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
