// Mocks generated by Mockito 5.4.4 from annotations
// in personal_finance_tracker/test/infrastructure/services/report_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:decimal/decimal.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_finance_tracker/domain/entities/category.dart' as _i4;
import 'package:personal_finance_tracker/domain/entities/transaction.dart'
    as _i2;
import 'package:personal_finance_tracker/domain/repositories/transaction_repository.dart'
    as _i6;
import 'package:personal_finance_tracker/domain/services/category_service.dart'
    as _i5;
import 'package:personal_finance_tracker/domain/value_objects/date_range.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransaction_0 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDecimal_1 extends _i1.SmartFake implements _i3.Decimal {
  _FakeDecimal_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_2 extends _i1.SmartFake implements _i4.Category {
  _FakeCategory_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryHierarchy_3 extends _i1.SmartFake
    implements _i5.CategoryHierarchy {
  _FakeCategoryHierarchy_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i6.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Transaction> create(
    String? userId,
    _i6.TransactionInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            userId,
            input,
          ],
        ),
        returnValue: _i7.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #create,
            [
              userId,
              input,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Transaction>);

  @override
  _i7.Future<_i2.Transaction> update(
    String? id,
    _i6.TransactionInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            input,
          ],
        ),
        returnValue: _i7.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #update,
            [
              id,
              input,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Transaction>);

  @override
  _i7.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.Transaction?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i7.Future<_i2.Transaction?>.value(),
      ) as _i7.Future<_i2.Transaction?>);

  @override
  _i7.Future<List<_i2.Transaction>> getAll({
    required String? userId,
    _i8.DateRange? range,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #userId: userId,
            #range: range,
            #categoryId: categoryId,
          },
        ),
        returnValue:
            _i7.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
      ) as _i7.Future<List<_i2.Transaction>>);

  @override
  _i7.Stream<List<_i2.Transaction>> watchAll({
    required String? userId,
    _i8.DateRange? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {
            #userId: userId,
            #range: range,
          },
        ),
        returnValue: _i7.Stream<List<_i2.Transaction>>.empty(),
      ) as _i7.Stream<List<_i2.Transaction>>);

  @override
  _i7.Future<_i3.Decimal> calculateBalance(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBalance,
          [userId],
        ),
        returnValue: _i7.Future<_i3.Decimal>.value(_FakeDecimal_1(
          this,
          Invocation.method(
            #calculateBalance,
            [userId],
          ),
        )),
      ) as _i7.Future<_i3.Decimal>);

  @override
  _i7.Future<Map<String, _i3.Decimal>> getSpendingBreakdown({
    required String? userId,
    required _i8.DateRange? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpendingBreakdown,
          [],
          {
            #userId: userId,
            #range: range,
          },
        ),
        returnValue:
            _i7.Future<Map<String, _i3.Decimal>>.value(<String, _i3.Decimal>{}),
      ) as _i7.Future<Map<String, _i3.Decimal>>);
}

/// A class which mocks [CategoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryService extends _i1.Mock implements _i5.CategoryService {
  MockCategoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.Category>> getDefaultCategories(_i9.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultCategories,
          [locale],
        ),
        returnValue: _i7.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i7.Future<List<_i4.Category>>);

  @override
  _i7.Future<_i4.Category> createCustomCategory(
    String? userId,
    _i5.CategoryInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomCategory,
          [
            userId,
            input,
          ],
        ),
        returnValue: _i7.Future<_i4.Category>.value(_FakeCategory_2(
          this,
          Invocation.method(
            #createCustomCategory,
            [
              userId,
              input,
            ],
          ),
        )),
      ) as _i7.Future<_i4.Category>);

  @override
  _i7.Future<_i4.Category> updateCategory(
    String? id,
    _i5.CategoryInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            input,
          ],
        ),
        returnValue: _i7.Future<_i4.Category>.value(_FakeCategory_2(
          this,
          Invocation.method(
            #updateCategory,
            [
              id,
              input,
            ],
          ),
        )),
      ) as _i7.Future<_i4.Category>);

  @override
  _i7.Future<void> deleteCategory(
    String? id,
    String? reassignToCategoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [
            id,
            reassignToCategoryId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.Category>> getAllCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [userId],
        ),
        returnValue: _i7.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i7.Future<List<_i4.Category>>);

  @override
  _i7.Future<_i5.CategoryHierarchy> getCategoryTree(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryTree,
          [userId],
        ),
        returnValue:
            _i7.Future<_i5.CategoryHierarchy>.value(_FakeCategoryHierarchy_3(
          this,
          Invocation.method(
            #getCategoryTree,
            [userId],
          ),
        )),
      ) as _i7.Future<_i5.CategoryHierarchy>);

  @override
  _i7.Future<_i4.Category?> getCategoryById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i7.Future<_i4.Category?>.value(),
      ) as _i7.Future<_i4.Category?>);

  @override
  _i7.Future<bool> hasTransactions(String? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #hasTransactions,
          [categoryId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i4.Category>> getChildCategories(
    String? parentCategoryId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildCategories,
          [
            parentCategoryId,
            userId,
          ],
        ),
        returnValue: _i7.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i7.Future<List<_i4.Category>>);
}
