// Mocks generated by Mockito 5.4.4 from annotations
// in personal_finance_tracker/test/infrastructure/services/sync_manager_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:connectivity_plus/connectivity_plus.dart' as _i10;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i11;
import 'package:decimal/decimal.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_finance_tracker/domain/entities/budget.dart' as _i7;
import 'package:personal_finance_tracker/domain/entities/category.dart' as _i4;
import 'package:personal_finance_tracker/domain/entities/savings_goal.dart'
    as _i5;
import 'package:personal_finance_tracker/domain/entities/transaction.dart'
    as _i3;
import 'package:personal_finance_tracker/domain/value_objects/date_range.dart'
    as _i13;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/budget_local_data_source.dart'
    as _i16;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/category_local_data_source.dart'
    as _i14;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/hive_type_adapters.dart'
    as _i2;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/savings_goal_local_data_source.dart'
    as _i15;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/sync_queue_local_data_source.dart'
    as _i8;
import 'package:personal_finance_tracker/infrastructure/data_sources/local/transaction_local_data_source.dart'
    as _i12;
import 'package:personal_finance_tracker/infrastructure/datasources/cloud/budget_cloud_data_source.dart'
    as _i20;
import 'package:personal_finance_tracker/infrastructure/datasources/cloud/category_cloud_data_source.dart'
    as _i18;
import 'package:personal_finance_tracker/infrastructure/datasources/cloud/savings_goal_cloud_data_source.dart'
    as _i19;
import 'package:personal_finance_tracker/infrastructure/datasources/cloud/transaction_cloud_data_source.dart'
    as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncQueueItem_0 extends _i1.SmartFake implements _i2.SyncQueueItem {
  _FakeSyncQueueItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_1 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_2 extends _i1.SmartFake implements _i4.Category {
  _FakeCategory_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSavingsGoal_3 extends _i1.SmartFake implements _i5.SavingsGoal {
  _FakeSavingsGoal_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDecimal_4 extends _i1.SmartFake implements _i6.Decimal {
  _FakeDecimal_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBudget_5 extends _i1.SmartFake implements _i7.Budget {
  _FakeBudget_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncQueueLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueueLocalDataSource extends _i1.Mock
    implements _i8.SyncQueueLocalDataSource {
  MockSyncQueueLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.SyncQueueItem> enqueue(_i2.SyncQueueItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [item],
        ),
        returnValue: _i9.Future<_i2.SyncQueueItem>.value(_FakeSyncQueueItem_0(
          this,
          Invocation.method(
            #enqueue,
            [item],
          ),
        )),
      ) as _i9.Future<_i2.SyncQueueItem>);

  @override
  _i9.Future<void> dequeue(String? id) => (super.noSuchMethod(
        Invocation.method(
          #dequeue,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i2.SyncQueueItem?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i2.SyncQueueItem?>.value(),
      ) as _i9.Future<_i2.SyncQueueItem?>);

  @override
  _i9.Future<List<_i2.SyncQueueItem>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i9.Future<List<_i2.SyncQueueItem>>.value(<_i2.SyncQueueItem>[]),
      ) as _i9.Future<List<_i2.SyncQueueItem>>);

  @override
  _i9.Future<List<_i2.SyncQueueItem>> getByEntityType(String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByEntityType,
          [entityType],
        ),
        returnValue:
            _i9.Future<List<_i2.SyncQueueItem>>.value(<_i2.SyncQueueItem>[]),
      ) as _i9.Future<List<_i2.SyncQueueItem>>);

  @override
  _i9.Future<List<_i2.SyncQueueItem>> getByOperation(String? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByOperation,
          [operation],
        ),
        returnValue:
            _i9.Future<List<_i2.SyncQueueItem>>.value(<_i2.SyncQueueItem>[]),
      ) as _i9.Future<List<_i2.SyncQueueItem>>);

  @override
  _i9.Future<List<_i2.SyncQueueItem>> getRetryItems() => (super.noSuchMethod(
        Invocation.method(
          #getRetryItems,
          [],
        ),
        returnValue:
            _i9.Future<List<_i2.SyncQueueItem>>.value(<_i2.SyncQueueItem>[]),
      ) as _i9.Future<List<_i2.SyncQueueItem>>);

  @override
  _i9.Future<_i2.SyncQueueItem> incrementRetryCount(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementRetryCount,
          [id],
        ),
        returnValue: _i9.Future<_i2.SyncQueueItem>.value(_FakeSyncQueueItem_0(
          this,
          Invocation.method(
            #incrementRetryCount,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.SyncQueueItem>);

  @override
  _i9.Future<int> getCount() => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<bool> isEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isEmpty,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchEnqueue(List<_i2.SyncQueueItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchEnqueue,
          [items],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDequeue(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDequeue,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i2.SyncQueueItem>> watchAll() => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
        ),
        returnValue: _i9.Stream<List<_i2.SyncQueueItem>>.empty(),
      ) as _i9.Stream<List<_i2.SyncQueueItem>>);

  @override
  _i9.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i10.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i11.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i9.Stream<List<_i11.ConnectivityResult>>.empty(),
      ) as _i9.Stream<List<_i11.ConnectivityResult>>);

  @override
  _i9.Future<List<_i11.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i9.Future<List<_i11.ConnectivityResult>>.value(
            <_i11.ConnectivityResult>[]),
      ) as _i9.Future<List<_i11.ConnectivityResult>>);
}

/// A class which mocks [TransactionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDataSource extends _i1.Mock
    implements _i12.TransactionLocalDataSource {
  MockTransactionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.Transaction> create(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [transaction],
        ),
        returnValue: _i9.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #create,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i3.Transaction>);

  @override
  _i9.Future<_i3.Transaction> update(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [transaction],
        ),
        returnValue: _i9.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #update,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i3.Transaction>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.Transaction?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i3.Transaction?>.value(),
      ) as _i9.Future<_i3.Transaction?>);

  @override
  _i9.Future<List<_i3.Transaction>> getAll({
    required String? userId,
    _i13.DateRange? dateRange,
    String? categoryId,
    _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getByDateRange({
    required String? userId,
    required _i13.DateRange? dateRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDateRange,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getByCategory({
    required String? userId,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [],
          {
            #userId: userId,
            #categoryId: categoryId,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getByType({
    required String? userId,
    required _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [],
          {
            #userId: userId,
            #type: type,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getPendingSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSync,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getConflicts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Stream<List<_i3.Transaction>> watchAll({
    required String? userId,
    _i13.DateRange? dateRange,
    String? categoryId,
    _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue: _i9.Stream<List<_i3.Transaction>>.empty(),
      ) as _i9.Stream<List<_i3.Transaction>>);

  @override
  _i9.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> clearAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [userId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchCreate(List<_i3.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [transactions],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i3.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [transactions],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [CategoryLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryLocalDataSource extends _i1.Mock
    implements _i14.CategoryLocalDataSource {
  MockCategoryLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.Category> create(_i4.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [category],
        ),
        returnValue: _i9.Future<_i4.Category>.value(_FakeCategory_2(
          this,
          Invocation.method(
            #create,
            [category],
          ),
        )),
      ) as _i9.Future<_i4.Category>);

  @override
  _i9.Future<_i4.Category> update(_i4.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [category],
        ),
        returnValue: _i9.Future<_i4.Category>.value(_FakeCategory_2(
          this,
          Invocation.method(
            #update,
            [category],
          ),
        )),
      ) as _i9.Future<_i4.Category>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.Category?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i4.Category?>.value(),
      ) as _i9.Future<_i4.Category?>);

  @override
  _i9.Future<List<_i4.Category>> getAll({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getDefaultCategories({String? locale}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultCategories,
          [],
          {#locale: locale},
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getCustomCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomCategories,
          [userId],
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getRootCategories({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRootCategories,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getChildCategories({
    required String? parentCategoryId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildCategories,
          [],
          {
            #parentCategoryId: parentCategoryId,
            #userId: userId,
          },
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<Map<_i4.Category, List<_i4.Category>>> getCategoryHierarchy(
          {String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryHierarchy,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<Map<_i4.Category, List<_i4.Category>>>.value(
            <_i4.Category, List<_i4.Category>>{}),
      ) as _i9.Future<Map<_i4.Category, List<_i4.Category>>>);

  @override
  _i9.Future<bool> hasChildren(
    String? categoryId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasChildren,
          [categoryId],
          {#userId: userId},
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<_i4.Category>> getAncestors(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAncestors,
          [categoryId],
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<bool> hasCircularReference(
    String? categoryId,
    String? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasCircularReference,
          [
            categoryId,
            parentId,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Stream<List<_i4.Category>> watchAll({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Stream<List<_i4.Category>>.empty(),
      ) as _i9.Stream<List<_i4.Category>>);

  @override
  _i9.Future<int> getCount({String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> clearCustomCategories(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearCustomCategories,
          [userId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchCreate(List<_i4.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [categories],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i4.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [categories],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [SavingsGoalLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavingsGoalLocalDataSource extends _i1.Mock
    implements _i15.SavingsGoalLocalDataSource {
  MockSavingsGoalLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.SavingsGoal> create(_i5.SavingsGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [goal],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #create,
            [goal],
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<_i5.SavingsGoal> update(_i5.SavingsGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [goal],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #update,
            [goal],
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.SavingsGoal?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal?>.value(),
      ) as _i9.Future<_i5.SavingsGoal?>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getAll(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getActive(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getCompleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompleted,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getOverdue(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOverdue,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getWithReminders(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWithReminders,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getNeedingReminder(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNeedingReminder,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<_i5.SavingsGoal> addContribution({
    required String? goalId,
    required _i6.Decimal? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContribution,
          [],
          {
            #goalId: goalId,
            #amount: amount,
          },
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #addContribution,
            [],
            {
              #goalId: goalId,
              #amount: amount,
            },
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<_i5.SavingsGoal> subtractAmount({
    required String? goalId,
    required _i6.Decimal? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subtractAmount,
          [],
          {
            #goalId: goalId,
            #amount: amount,
          },
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #subtractAmount,
            [],
            {
              #goalId: goalId,
              #amount: amount,
            },
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<_i5.SavingsGoal> updateLastReminderSent(String? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReminderSent,
          [goalId],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #updateLastReminderSent,
            [goalId],
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getPendingSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSync,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getConflicts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Stream<List<_i5.SavingsGoal>> watchAll(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [userId],
        ),
        returnValue: _i9.Stream<List<_i5.SavingsGoal>>.empty(),
      ) as _i9.Stream<List<_i5.SavingsGoal>>);

  @override
  _i9.Stream<_i5.SavingsGoal?> watchGoal(String? goalId) => (super.noSuchMethod(
        Invocation.method(
          #watchGoal,
          [goalId],
        ),
        returnValue: _i9.Stream<_i5.SavingsGoal?>.empty(),
      ) as _i9.Stream<_i5.SavingsGoal?>);

  @override
  _i9.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<_i6.Decimal> getTotalTargetAmount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalTargetAmount,
          [userId],
        ),
        returnValue: _i9.Future<_i6.Decimal>.value(_FakeDecimal_4(
          this,
          Invocation.method(
            #getTotalTargetAmount,
            [userId],
          ),
        )),
      ) as _i9.Future<_i6.Decimal>);

  @override
  _i9.Future<_i6.Decimal> getTotalCurrentAmount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalCurrentAmount,
          [userId],
        ),
        returnValue: _i9.Future<_i6.Decimal>.value(_FakeDecimal_4(
          this,
          Invocation.method(
            #getTotalCurrentAmount,
            [userId],
          ),
        )),
      ) as _i9.Future<_i6.Decimal>);

  @override
  _i9.Future<void> clearAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [userId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchCreate(List<_i5.SavingsGoal>? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [goals],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i5.SavingsGoal>? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [goals],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [BudgetLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetLocalDataSource extends _i1.Mock
    implements _i16.BudgetLocalDataSource {
  MockBudgetLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Budget> create(_i7.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [budget],
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #create,
            [budget],
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<_i7.Budget> update(_i7.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [budget],
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #update,
            [budget],
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i7.Budget?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i7.Budget?>.value(),
      ) as _i9.Future<_i7.Budget?>);

  @override
  _i9.Future<List<_i7.Budget>> getAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [userId],
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getByMonth({
    required String? userId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByMonth,
          [],
          {
            #userId: userId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getCurrentMonth(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonth,
          [userId],
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<_i7.Budget?> getByCategoryAndMonth({
    required String? userId,
    required String? categoryId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategoryAndMonth,
          [],
          {
            #userId: userId,
            #categoryId: categoryId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Future<_i7.Budget?>.value(),
      ) as _i9.Future<_i7.Budget?>);

  @override
  _i9.Future<List<_i7.Budget>> getNearLimit(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearLimit,
          [userId],
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getOverLimit(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOverLimit,
          [userId],
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<_i7.Budget> updateSpending({
    required String? budgetId,
    required _i6.Decimal? newSpending,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpending,
          [],
          {
            #budgetId: budgetId,
            #newSpending: newSpending,
          },
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #updateSpending,
            [],
            {
              #budgetId: budgetId,
              #newSpending: newSpending,
            },
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<_i7.Budget> addSpending({
    required String? budgetId,
    required _i6.Decimal? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSpending,
          [],
          {
            #budgetId: budgetId,
            #amount: amount,
          },
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #addSpending,
            [],
            {
              #budgetId: budgetId,
              #amount: amount,
            },
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<_i7.Budget> subtractSpending({
    required String? budgetId,
    required _i6.Decimal? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subtractSpending,
          [],
          {
            #budgetId: budgetId,
            #amount: amount,
          },
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #subtractSpending,
            [],
            {
              #budgetId: budgetId,
              #amount: amount,
            },
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<_i7.Budget> resetSpending(String? budgetId) => (super.noSuchMethod(
        Invocation.method(
          #resetSpending,
          [budgetId],
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #resetSpending,
            [budgetId],
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<void> resetMonthlyBudgets({
    required String? userId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetMonthlyBudgets,
          [],
          {
            #userId: userId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> resetCurrentMonthBudgets(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetCurrentMonthBudgets,
          [userId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i7.Budget>> copyToNextMonth({
    required String? userId,
    required int? fromMonth,
    required int? fromYear,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyToNextMonth,
          [],
          {
            #userId: userId,
            #fromMonth: fromMonth,
            #fromYear: fromYear,
          },
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getPendingSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSync,
          [userId],
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getConflicts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [userId],
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Stream<List<_i7.Budget>> watchAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [userId],
        ),
        returnValue: _i9.Stream<List<_i7.Budget>>.empty(),
      ) as _i9.Stream<List<_i7.Budget>>);

  @override
  _i9.Stream<List<_i7.Budget>> watchMonth({
    required String? userId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMonth,
          [],
          {
            #userId: userId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Stream<List<_i7.Budget>>.empty(),
      ) as _i9.Stream<List<_i7.Budget>>);

  @override
  _i9.Stream<_i7.Budget?> watchBudget(String? budgetId) => (super.noSuchMethod(
        Invocation.method(
          #watchBudget,
          [budgetId],
        ),
        returnValue: _i9.Stream<_i7.Budget?>.empty(),
      ) as _i9.Stream<_i7.Budget?>);

  @override
  _i9.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> clearAll(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [userId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchCreate(List<_i7.Budget>? budgets) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [budgets],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i7.Budget>? budgets) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [budgets],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [TransactionCloudDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionCloudDataSource extends _i1.Mock
    implements _i17.TransactionCloudDataSource {
  MockTransactionCloudDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.Transaction> create(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [transaction],
        ),
        returnValue: _i9.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #create,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i3.Transaction>);

  @override
  _i9.Future<_i3.Transaction> update(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [transaction],
        ),
        returnValue: _i9.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #update,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i3.Transaction>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.Transaction?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i3.Transaction?>.value(),
      ) as _i9.Future<_i3.Transaction?>);

  @override
  _i9.Future<List<_i3.Transaction>> getAll({
    required String? userId,
    _i13.DateRange? dateRange,
    String? categoryId,
    _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getByDateRange({
    required String? userId,
    required _i13.DateRange? dateRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDateRange,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getByCategory({
    required String? userId,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [],
          {
            #userId: userId,
            #categoryId: categoryId,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getByType({
    required String? userId,
    required _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [],
          {
            #userId: userId,
            #type: type,
          },
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getPendingSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSync,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<List<_i3.Transaction>> getConflicts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Stream<List<_i3.Transaction>> watchAll({
    required String? userId,
    _i13.DateRange? dateRange,
    String? categoryId,
    _i3.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue: _i9.Stream<List<_i3.Transaction>>.empty(),
      ) as _i9.Stream<List<_i3.Transaction>>);

  @override
  _i9.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> batchCreate(List<_i3.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [transactions],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i3.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [transactions],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [CategoryCloudDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryCloudDataSource extends _i1.Mock
    implements _i18.CategoryCloudDataSource {
  MockCategoryCloudDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.Category> create(_i4.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [category],
        ),
        returnValue: _i9.Future<_i4.Category>.value(_FakeCategory_2(
          this,
          Invocation.method(
            #create,
            [category],
          ),
        )),
      ) as _i9.Future<_i4.Category>);

  @override
  _i9.Future<_i4.Category> update(_i4.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [category],
        ),
        returnValue: _i9.Future<_i4.Category>.value(_FakeCategory_2(
          this,
          Invocation.method(
            #update,
            [category],
          ),
        )),
      ) as _i9.Future<_i4.Category>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.Category?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i4.Category?>.value(),
      ) as _i9.Future<_i4.Category?>);

  @override
  _i9.Future<List<_i4.Category>> getAll({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getDefaultCategories({String? locale}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultCategories,
          [],
          {#locale: locale},
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getCustomCategories(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomCategories,
          [userId],
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getChildCategories(String? parentCategoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildCategories,
          [parentCategoryId],
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<List<_i4.Category>> getRootCategories({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRootCategories,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i9.Future<List<_i4.Category>>);

  @override
  _i9.Future<void> batchCreate(List<_i4.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [categories],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i4.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [categories],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [SavingsGoalCloudDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavingsGoalCloudDataSource extends _i1.Mock
    implements _i19.SavingsGoalCloudDataSource {
  MockSavingsGoalCloudDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.SavingsGoal> create(_i5.SavingsGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [goal],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #create,
            [goal],
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<_i5.SavingsGoal> update(_i5.SavingsGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [goal],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal>.value(_FakeSavingsGoal_3(
          this,
          Invocation.method(
            #update,
            [goal],
          ),
        )),
      ) as _i9.Future<_i5.SavingsGoal>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.SavingsGoal?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i5.SavingsGoal?>.value(),
      ) as _i9.Future<_i5.SavingsGoal?>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getAll({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getActive({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getCompleted({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompleted,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getOverdue({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOverdue,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<List<_i5.SavingsGoal>> getWithReminders(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWithReminders,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i9.Future<List<_i5.SavingsGoal>>.value(<_i5.SavingsGoal>[]),
      ) as _i9.Future<List<_i5.SavingsGoal>>);

  @override
  _i9.Stream<_i5.SavingsGoal?> watchGoal(String? id) => (super.noSuchMethod(
        Invocation.method(
          #watchGoal,
          [id],
        ),
        returnValue: _i9.Stream<_i5.SavingsGoal?>.empty(),
      ) as _i9.Stream<_i5.SavingsGoal?>);

  @override
  _i9.Stream<List<_i5.SavingsGoal>> watchAll({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Stream<List<_i5.SavingsGoal>>.empty(),
      ) as _i9.Stream<List<_i5.SavingsGoal>>);

  @override
  _i9.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> batchCreate(List<_i5.SavingsGoal>? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [goals],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i5.SavingsGoal>? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [goals],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [BudgetCloudDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetCloudDataSource extends _i1.Mock
    implements _i20.BudgetCloudDataSource {
  MockBudgetCloudDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Budget> create(_i7.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [budget],
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #create,
            [budget],
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<_i7.Budget> update(_i7.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [budget],
        ),
        returnValue: _i9.Future<_i7.Budget>.value(_FakeBudget_5(
          this,
          Invocation.method(
            #update,
            [budget],
          ),
        )),
      ) as _i9.Future<_i7.Budget>);

  @override
  _i9.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i7.Budget?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i7.Budget?>.value(),
      ) as _i9.Future<_i7.Budget?>);

  @override
  _i9.Future<List<_i7.Budget>> getAll({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getByMonth({
    required String? userId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByMonth,
          [],
          {
            #userId: userId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<_i7.Budget?> getByCategoryAndMonth({
    required String? userId,
    required String? categoryId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategoryAndMonth,
          [],
          {
            #userId: userId,
            #categoryId: categoryId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Future<_i7.Budget?>.value(),
      ) as _i9.Future<_i7.Budget?>);

  @override
  _i9.Future<List<_i7.Budget>> getByCategory({
    required String? userId,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [],
          {
            #userId: userId,
            #categoryId: categoryId,
          },
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getAlerting({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlerting,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Future<List<_i7.Budget>> getCurrentMonth({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonth,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Future<List<_i7.Budget>>.value(<_i7.Budget>[]),
      ) as _i9.Future<List<_i7.Budget>>);

  @override
  _i9.Stream<List<_i7.Budget>> watchAll({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {#userId: userId},
        ),
        returnValue: _i9.Stream<List<_i7.Budget>>.empty(),
      ) as _i9.Stream<List<_i7.Budget>>);

  @override
  _i9.Stream<List<_i7.Budget>> watchByMonth({
    required String? userId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchByMonth,
          [],
          {
            #userId: userId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Stream<List<_i7.Budget>>.empty(),
      ) as _i9.Stream<List<_i7.Budget>>);

  @override
  _i9.Future<int> getCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [userId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> batchCreate(List<_i7.Budget>? budgets) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreate,
          [budgets],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdate(List<_i7.Budget>? budgets) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [budgets],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> batchDelete(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDelete,
          [ids],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> resetMonthlyBudgets({
    required String? userId,
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetMonthlyBudgets,
          [],
          {
            #userId: userId,
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
