// Mocks generated by Mockito 5.4.4 from annotations
// in personal_finance_tracker/test/application/use_cases/process_receipt_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:personal_finance_tracker/domain/services/receipt_processor.dart'
    as _i2;
import 'package:personal_finance_tracker/domain/value_objects/receipt_data.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReceiptProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockReceiptProcessor extends _i1.Mock implements _i2.ReceiptProcessor {
  MockReceiptProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> storeReceiptImage(_i4.File? image) => (super.noSuchMethod(
        Invocation.method(
          #storeReceiptImage,
          [image],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #storeReceiptImage,
            [image],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i6.ReceiptData?> extractData(_i4.File? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractData,
          [image],
        ),
        returnValue: _i3.Future<_i6.ReceiptData?>.value(),
      ) as _i3.Future<_i6.ReceiptData?>);

  @override
  _i3.Future<_i4.File?> getReceiptImage(String? imageId) => (super.noSuchMethod(
        Invocation.method(
          #getReceiptImage,
          [imageId],
        ),
        returnValue: _i3.Future<_i4.File?>.value(),
      ) as _i3.Future<_i4.File?>);

  @override
  _i3.Future<void> deleteReceiptImage(String? imageId) => (super.noSuchMethod(
        Invocation.method(
          #deleteReceiptImage,
          [imageId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
