// Mocks generated by Mockito 5.4.4 from annotations
// in personal_finance_tracker/test/application/use_cases/process_payment_contribution_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i9;

import 'package:decimal/decimal.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_finance_tracker/domain/entities/savings_goal.dart'
    as _i4;
import 'package:personal_finance_tracker/domain/entities/transaction.dart'
    as _i6;
import 'package:personal_finance_tracker/domain/repositories/transaction_repository.dart'
    as _i13;
import 'package:personal_finance_tracker/domain/services/payment_gateway_service.dart'
    as _i7;
import 'package:personal_finance_tracker/domain/services/savings_goal_manager.dart'
    as _i12;
import 'package:personal_finance_tracker/domain/value_objects/date_range.dart'
    as _i14;
import 'package:personal_finance_tracker/domain/value_objects/payment_provider.dart'
    as _i8;
import 'package:personal_finance_tracker/domain/value_objects/payment_request.dart'
    as _i11;
import 'package:personal_finance_tracker/domain/value_objects/payment_result.dart'
    as _i3;
import 'package:personal_finance_tracker/domain/value_objects/payment_session.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaymentSession_0 extends _i1.SmartFake
    implements _i2.PaymentSession {
  _FakePaymentSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_1 extends _i1.SmartFake implements _i3.PaymentResult {
  _FakePaymentResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSavingsGoal_2 extends _i1.SmartFake implements _i4.SavingsGoal {
  _FakeSavingsGoal_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDecimal_3 extends _i1.SmartFake implements _i5.Decimal {
  _FakeDecimal_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_4 extends _i1.SmartFake implements _i6.Transaction {
  _FakeTransaction_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaymentGatewayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentGatewayService extends _i1.Mock
    implements _i7.PaymentGatewayService {
  MockPaymentGatewayService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.PaymentProvider> getAvailableProviders(_i9.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableProviders,
          [locale],
        ),
        returnValue: <_i8.PaymentProvider>[],
      ) as List<_i8.PaymentProvider>);

  @override
  _i10.Future<_i2.PaymentSession> initiatePayment(
          _i11.PaymentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiatePayment,
          [request],
        ),
        returnValue:
            _i10.Future<_i2.PaymentSession>.value(_FakePaymentSession_0(
          this,
          Invocation.method(
            #initiatePayment,
            [request],
          ),
        )),
      ) as _i10.Future<_i2.PaymentSession>);

  @override
  _i10.Future<_i3.PaymentResult> verifyPayment(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPayment,
          [sessionId],
        ),
        returnValue: _i10.Future<_i3.PaymentResult>.value(_FakePaymentResult_1(
          this,
          Invocation.method(
            #verifyPayment,
            [sessionId],
          ),
        )),
      ) as _i10.Future<_i3.PaymentResult>);

  @override
  _i10.Future<_i3.PaymentResult> handleCallback(
          Map<String, dynamic>? callbackData) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleCallback,
          [callbackData],
        ),
        returnValue: _i10.Future<_i3.PaymentResult>.value(_FakePaymentResult_1(
          this,
          Invocation.method(
            #handleCallback,
            [callbackData],
          ),
        )),
      ) as _i10.Future<_i3.PaymentResult>);
}

/// A class which mocks [SavingsGoalManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavingsGoalManager extends _i1.Mock
    implements _i12.SavingsGoalManager {
  MockSavingsGoalManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.SavingsGoal> create(
    String? userId,
    _i12.SavingsGoalInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            userId,
            input,
          ],
        ),
        returnValue: _i10.Future<_i4.SavingsGoal>.value(_FakeSavingsGoal_2(
          this,
          Invocation.method(
            #create,
            [
              userId,
              input,
            ],
          ),
        )),
      ) as _i10.Future<_i4.SavingsGoal>);

  @override
  _i10.Future<_i4.SavingsGoal> contribute(
    String? goalId,
    _i5.Decimal? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #contribute,
          [
            goalId,
            amount,
          ],
        ),
        returnValue: _i10.Future<_i4.SavingsGoal>.value(_FakeSavingsGoal_2(
          this,
          Invocation.method(
            #contribute,
            [
              goalId,
              amount,
            ],
          ),
        )),
      ) as _i10.Future<_i4.SavingsGoal>);

  @override
  _i10.Future<_i4.SavingsGoal> update(
    String? id,
    _i12.SavingsGoalInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            input,
          ],
        ),
        returnValue: _i10.Future<_i4.SavingsGoal>.value(_FakeSavingsGoal_2(
          this,
          Invocation.method(
            #update,
            [
              id,
              input,
            ],
          ),
        )),
      ) as _i10.Future<_i4.SavingsGoal>);

  @override
  _i10.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i4.SavingsGoal>> getAll(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i4.SavingsGoal>>.value(<_i4.SavingsGoal>[]),
      ) as _i10.Future<List<_i4.SavingsGoal>>);

  @override
  _i10.Future<_i4.SavingsGoal?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i10.Future<_i4.SavingsGoal?>.value(),
      ) as _i10.Future<_i4.SavingsGoal?>);

  @override
  _i10.Stream<_i4.SavingsGoal?> watchGoal(String? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchGoal,
          [goalId],
        ),
        returnValue: _i10.Stream<_i4.SavingsGoal?>.empty(),
      ) as _i10.Stream<_i4.SavingsGoal?>);

  @override
  _i10.Stream<List<_i4.SavingsGoal>> watchAll(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [userId],
        ),
        returnValue: _i10.Stream<List<_i4.SavingsGoal>>.empty(),
      ) as _i10.Stream<List<_i4.SavingsGoal>>);

  @override
  _i10.Future<_i5.Decimal> calculateSuggestedContribution(String? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateSuggestedContribution,
          [goalId],
        ),
        returnValue: _i10.Future<_i5.Decimal>.value(_FakeDecimal_3(
          this,
          Invocation.method(
            #calculateSuggestedContribution,
            [goalId],
          ),
        )),
      ) as _i10.Future<_i5.Decimal>);

  @override
  _i10.Future<List<_i4.SavingsGoal>> getActive(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i4.SavingsGoal>>.value(<_i4.SavingsGoal>[]),
      ) as _i10.Future<List<_i4.SavingsGoal>>);

  @override
  _i10.Future<List<_i4.SavingsGoal>> getCompleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompleted,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i4.SavingsGoal>>.value(<_i4.SavingsGoal>[]),
      ) as _i10.Future<List<_i4.SavingsGoal>>);

  @override
  _i10.Future<List<_i4.SavingsGoal>> getOverdue(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOverdue,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i4.SavingsGoal>>.value(<_i4.SavingsGoal>[]),
      ) as _i10.Future<List<_i4.SavingsGoal>>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i13.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i6.Transaction> create(
    String? userId,
    _i13.TransactionInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            userId,
            input,
          ],
        ),
        returnValue: _i10.Future<_i6.Transaction>.value(_FakeTransaction_4(
          this,
          Invocation.method(
            #create,
            [
              userId,
              input,
            ],
          ),
        )),
      ) as _i10.Future<_i6.Transaction>);

  @override
  _i10.Future<_i6.Transaction> update(
    String? id,
    _i13.TransactionInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            input,
          ],
        ),
        returnValue: _i10.Future<_i6.Transaction>.value(_FakeTransaction_4(
          this,
          Invocation.method(
            #update,
            [
              id,
              input,
            ],
          ),
        )),
      ) as _i10.Future<_i6.Transaction>);

  @override
  _i10.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i6.Transaction?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i10.Future<_i6.Transaction?>.value(),
      ) as _i10.Future<_i6.Transaction?>);

  @override
  _i10.Future<List<_i6.Transaction>> getAll({
    required String? userId,
    _i14.DateRange? range,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #userId: userId,
            #range: range,
            #categoryId: categoryId,
          },
        ),
        returnValue:
            _i10.Future<List<_i6.Transaction>>.value(<_i6.Transaction>[]),
      ) as _i10.Future<List<_i6.Transaction>>);

  @override
  _i10.Stream<List<_i6.Transaction>> watchAll({
    required String? userId,
    _i14.DateRange? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
          {
            #userId: userId,
            #range: range,
          },
        ),
        returnValue: _i10.Stream<List<_i6.Transaction>>.empty(),
      ) as _i10.Stream<List<_i6.Transaction>>);

  @override
  _i10.Future<_i5.Decimal> calculateBalance(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBalance,
          [userId],
        ),
        returnValue: _i10.Future<_i5.Decimal>.value(_FakeDecimal_3(
          this,
          Invocation.method(
            #calculateBalance,
            [userId],
          ),
        )),
      ) as _i10.Future<_i5.Decimal>);

  @override
  _i10.Future<Map<String, _i5.Decimal>> getSpendingBreakdown({
    required String? userId,
    required _i14.DateRange? range,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpendingBreakdown,
          [],
          {
            #userId: userId,
            #range: range,
          },
        ),
        returnValue: _i10.Future<Map<String, _i5.Decimal>>.value(
            <String, _i5.Decimal>{}),
      ) as _i10.Future<Map<String, _i5.Decimal>>);
}
